name: Validate merge request

on:
  pull_request:
    branches: 
      - master

jobs:
  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --no-restore --verbosity normal

  api-test:
    needs: unit-test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        working-directory: ./tests/api
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Run service instance
        run: docker-compose up -d
      - name: Test with pytest
        working-directory: ./tests/api
        run: pytest
      - name: Show api logs
        if: ${{ failure() }}
        run: docker-compose logs api
      - name: Stop service instance
        if: ${{ always() }}
        run: docker-compose stop
