name: Validate merge request
  
on:
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  api-test:
    needs: unit-test
    runs-on: ubuntu-20.04

    services:
      db:
        image: mvertes/alpine-mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        working-directory: ./tests/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build service
        run: docker build -t test-image .
      - name: Run service
        run: docker run -d -p 5300:80 test-image
      - name: Test with pytest
        working-directory: ./tests/api
        run: pytest
