name: Validate merge request

on:
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  api-test:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        working-directory: ./tests/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run service instance
        run: docker-compose up -d
      - name: Test with pytest
        working-directory: ./tests/api
        run: pytest
